FROM node:14-alpine AS development
WORKDIR /app
COPY package.json .
# COPY package-lock.json .
RUN npm install --no-optional
COPY . .
RUN [ "npm", "run", "build:prod" ]


FROM nginx:stable-alpine
COPY --from=development /app/build/ /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d