export const ActionTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  OPEN_TOASTER: 'OPEN_TOASTER',
  ALL_PROFILE_PICTURE: 'ALL_PROFILE_PICTURE',
  PROFILE_NAME: 'PROFILE_NAME',
};
