export const ActionTypes = {
  GET_USERS: "GET_USERS",
  SET_USERS: "SET_USERS",
  GET_PROFILE: "GET_PROFILE",
  SET_LOADING: "SET_LOADING",


  //profile
  GET_SKILLS: "GET_SKILLS",
  GET_DEGREE: "GET_DEGREE",
  GET_FIELD_OF_STUDY: "GET_FIELD_OF_STUDY"
};
