export const ActionTypes = {
  GET_USERS: "GET_USERS",
  SET_USERS: "SET_USERS",
  SET_EMAIL: "SET_EMAIL",
  CLEAR_EMAIL: "CLEAR_EMAIL",
  GET_PROFILE: "GET_PROFILE",
  SET_MOBILENUMBER: "SET_MOBILENUMBER",
  SET_LOADING: "SET_LOADING"
};
